name: AWS CDK CI for PUSH

on:
  push:
    branches:
      - "**"
    paths:
      - "**.ts"
      - ".github/workflows/push.yml"
      - "**.json"
      - "**.yaml"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STAGE: dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Build
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Test
        run: pnpm test -- --coverage
      - name: Test Coverage
        uses: codecov/codecov-action@v3
